Rule: Domain Trust Discovery and new IP checking domain
fireeye/capa-rules pull request #206
Opened 2020-12-21 01:51 UTC by johnk3r

#174

2020-12-21 16:26 UTC, mr-tz requested changes
Great, thank you. I only have a few comments.

2020-12-21 16:26 UTC, mr-tz commented on collection/network/domain-trust.yml
> +    name: Detect Domain Trust Discovery
Ideally this rules completes the sentence "this function may...". How about `get domain trust relationships`?

2020-12-21 16:26 UTC, mr-tz commented on collection/network/domain-trust.yml
> +      - string: /nltest.exe/i
How about removing the `.exe` to be a little more flexible?
Also should we add `DOMAIN_TRUSTS` as `nltest` can be used for various tasks?

2020-12-21 16:26 UTC, mr-tz commented on collection/network/capture-public-ip.yml
> +          - string: /api\.myip\.com/
👍

2020-12-22 01:07 UTC, johnk3r commented
Hello @mr-tz ,

tks for the suggestions. I changed the logic of the rule to improve detection and avoid false positives.

The only thing is to note that leaving only "nltest" detection did not occur. So I followed some examples of rules that use the character "*".

Also, if the malware contains two spaces (or more)  between commands the detection does not occur. So I left the strings separately. Do you have any smarter idea to avoid this "bypass"?

2020-12-22 09:24 UTC, mr-tz commented
That looks great. I tried the below modified rule on the test samples:
- combines `nltest` and domain arguments under an `and` statement
- removed trailing `.*` from `nltest` (capa assumes leading and trailing wildcards)
- escaped `/` character

```yaml
  features:
    - or:
      - and:
        - string: /nltest/i
        - or:
          - string: /\/domain_trusts/i
          - string: /\/dclist/i
          - string: /\/all_trusts/i
      - api: DsEnumerateDomainTrusts
```

What do you think of these changes?

2020-12-22 13:12 UTC, johnk3r commented
Great.

I adjusted the rule again.

2020-12-22 13:14 UTC, mr-tz approved these changes
lgtm! thank you!

2020-12-23 12:43 UTC, merged