Create get-enumeration-function.yml
fireeye/capa-rules pull request #209
Opened 2020-12-30 00:47 UTC by johnk3r

https://github.com/fireeye/capa-rules/issues/31

2020-12-30 19:02 UTC, williballenthin requested changes
looking good! just a couple of suggestions around the metadata.

2020-12-30 19:02 UTC, williballenthin commented on host-interaction/gui/window/get-enumeration-functions.yml
> +    name: get enumeration functions
lets call this: `enumerate GUI resources`

2020-12-30 19:02 UTC, williballenthin commented on host-interaction/gui/window/get-enumeration-functions.yml
> +    namespace: host-interaction/gui/window
since some of the APIs are not window-centric, lets relax the namespace to `host-interaction/gui`

2020-12-30 19:02 UTC, williballenthin commented on host-interaction/gui/window/get-enumeration-functions.yml
> +      - 021f49678cd633dc8cf99c61b3af3dda:0x40E44A
thanks for including so many examples!

2020-12-30 22:01 UTC, johnk3r commented
Thanks for the feedback.

I made the necessary changes.

2020-12-31 16:49 UTC, mike-hunhoff requested changes
Awesome, thank you for your work! It looks like an existing rule in the nursery contains a match for `EnumWindows`:

https://github.com/fireeye/capa-rules/blob/1ff994f7916d66e39b4b5b8dbb310d0e0b051f7f/nursery/enumerate-graphical-windows.yml#L11

Can you remove the above rule as part of this PR? Otherwise, everything looks great! 🚀

2021-01-04 08:01 UTC, mr-tz commented on host-interaction/gui/enumerate-gui-resources.yml
> +      - Discovery::Application Windows Discovery [T1010]
typo, should be `Application Window Discovery`, see https://attack.mitre.org/techniques/T1010/

2021-01-04 08:04 UTC, mr-tz commented
> 
> 
> Awesome, thank you for your work! It looks like an existing rule in the nursery contains a match for `EnumWindows`:
> 
> https://github.com/fireeye/capa-rules/blob/1ff994f7916d66e39b4b5b8dbb310d0e0b051f7f/nursery/enumerate-graphical-windows.yml#L11
> 
> Can you remove the above rule as part of this PR? Otherwise, everything looks great! 🚀

I'd vote to remove the nursery rule instead and keep this one with `EnumWindows`.

2021-01-05 12:45 UTC, johnk3r commented
> 
> 
> Awesome, thank you for your work! It looks like an existing rule in the nursery contains a match for `EnumWindows`:
> 
> https://github.com/fireeye/capa-rules/blob/1ff994f7916d66e39b4b5b8dbb310d0e0b051f7f/nursery/enumerate-graphical-windows.yml#L11
> 
> Can you remove the above rule as part of this PR? Otherwise, everything looks great! 🚀

Ok.

2021-01-05 12:45 UTC, johnk3r commented
> 
> 
> > Awesome, thank you for your work! It looks like an existing rule in the nursery contains a match for `EnumWindows`:
> > https://github.com/fireeye/capa-rules/blob/1ff994f7916d66e39b4b5b8dbb310d0e0b051f7f/nursery/enumerate-graphical-windows.yml#L11
> > 
> > Can you remove the above rule as part of this PR? Otherwise, everything looks great! 🚀
> 
> I'd vote to remove the nursery rule instead and keep this one with `EnumWindows`.

Removed.

2021-01-05 15:00 UTC, williballenthin approved these changes

2021-01-05 15:45 UTC, mike-hunhoff commented
> > Awesome, thank you for your work! It looks like an existing rule in the nursery contains a match for `EnumWindows`:
> > https://github.com/fireeye/capa-rules/blob/1ff994f7916d66e39b4b5b8dbb310d0e0b051f7f/nursery/enumerate-graphical-windows.yml#L11
> > 
> > Can you remove the above rule as part of this PR? Otherwise, everything looks great! 🚀
> 
> I'd vote to remove the nursery rule instead and keep this one with `EnumWindows`.

@johnk3r @mr-tz I apologize if I wasn't clear I originally meant to remove the nursery rule 😅

2021-01-05 15:47 UTC, mike-hunhoff approved these changes
Thank you for the changes @johnk3r! LGTM 🚀

2021-01-05 15:48 UTC, merged