create patch-process-command-line
fireeye/capa-rules pull request #235
Opened 2021-02-01 21:25 UTC by williballenthin

2021-02-02 12:16 UTC, mr-tz commented on nursery/patch-process-command-line
> +  features:
```suggestion  features:
    - and:
      - basic block:
        # example:
        #   mov     rbx, gs:60h
        #   lea     r9, [rsp+4A0h+flOldProtect] ; lpflOldProtect
        #   mov     edx, 8          ; dwSize
        #   mov     rcx, [rbx+20h]
        #   add     rcx, 70h ; 'p'  ; lpAddress
        #   lea     r8d, [rdx-4]    ; flNewProtect
        #   call    cs:VirtualProtect
        #   test    eax, eax
        - and:
          - characteristic: gs access
          - offset/x64: 0x60 = PEB
          - offset/x64: 0x20 = PEB->ProcessParameters
          - offset/x64: 0x70 = PEB->ProcessParameters->CommandLine
          - api: VirtualProtect
      - count(api(VirtualProtect)): 2 or more

```

2021-02-02 12:16 UTC, mr-tz requested changes
also needs renaming (add `.yml`)

2021-02-02 19:44 UTC, re-fox commented
Interesting technique.

The binary from the writeup is `d6a8bbe44fcf20c573b137dd0aef7b7862eb4bc845fc0157ed0a6de1197e6a21`.  I'll download that and load it up into a disassembler to validate the signature.

2021-02-02 20:01 UTC, williballenthin commented
@re-fox ah, good idea! i saw this technique in a sample that isn't public, and haven't yet found another case.

2021-02-03 08:12 UTC, mr-tz commented
I've cleaned up the git history and fixed the indent. Feel free to merge or we can wait for @re-fox's validation.

2021-02-03 14:40 UTC, re-fox commented
The version in the write-up uses `NtQueryInformationProcess` to get PEB and then performs a Read/WriteProcessMemory to modify CommandLine.  It looks like the sample @williballenthin analyzed is manually enumerating the PEB.  

The above rule is certainly worth a push, and we can come back to add the NtQueryInformationProcess -> ReadProcessMemory -> WriteProcessMemory technique mentioned.

2021-02-03 15:15 UTC, merged