New rules related to the amber packer
fireeye/capa-rules pull request #333
Opened 2021-04-22 16:39 UTC by gormaniac

There is an amber specific rule and a second that detects the shellcode loading function in the amber PE stub but should hopefully be a useful generic detection.
https://github.com/EgeBalci/amber

2021-04-22 16:42 UTC, williballenthin commented on anti-analysis/packer/amber/packed-with-amber.yml
> +      - Defense Evasion::Obfuscated Files or Information [T1027]
```suggestion
      - Defense Evasion::Obfuscated Files or Information [T1027]
    mbc:
      - Anti-Static Analysis::Software Packing [F0001]
```

2021-04-22 16:43 UTC, williballenthin commented on anti-analysis/packer/amber/packed-with-amber.yml
> +      - Defense Evasion::Obfuscated Files or Information [T1027]
```suggestion
      - Defense Evasion::Obfuscated Files or Information::Software Packing [T1027.002]
    mbc:
      - Anti-Static Analysis::Software Packing [F0001]      
```

2021-04-22 16:45 UTC, williballenthin commented on load-code/pe/potential-shellcode-loader.yml
> +        - api: kernel32.VirtualAlloc
i suspect that this rule may match on too many functions, especially those unrelated to shellcode loading.

i'd propose that we prefer the existing rules in `load-code/pe` https://github.com/fireeye/capa-rules/tree/master/load-code/pe

2021-04-22 16:52 UTC, williballenthin requested changes
i think the second rule should be removed from this PR, otherwise looking great, esp with minor tweaks to first rule metadata

2021-04-22 17:17 UTC, gormaniac commented
Removed the 2nd rule. I tried to fix the issues from the linter in `packed-with-amber.yml` but I am getting a different error this second time that I am not sure how to handle:
```
Error: Process completed with exit code 1.
```

2021-04-22 17:33 UTC, williballenthin commented
the (undocumented) trick is to look for "FAIL" in the linter output:

![image](https://user-images.githubusercontent.com/156560/115760328-76c7f000-a35e-11eb-85da-5fb822091a20.png)

this is simply saying that the referenced test file is not present. thats expected, because we have another open PR for it. so we can ignore that for now. in other words, the linter is happy.

2021-04-22 17:34 UTC, williballenthin commented on anti-analysis/packer/amber/packed-with-amber.yml
> +      - Defense Evasion::Obfuscated Files or Information [T1027]
```suggestion
      - Defense Evasion::Obfuscated Files or Information::Software Packing [T1027.002]
    mbc:
      - Anti-Static Analysis::Software Packing [F0001]
```

2021-04-22 17:34 UTC, williballenthin commented on anti-analysis/packer/amber/packed-with-amber.yml
> +      - Defense Evasion::Obfuscated Files or Information [T1027]
@gormaniac  you can hit "commit suggestion" above to easily merge this suggested change

2021-04-22 17:39 UTC, gormaniac commented on anti-analysis/packer/amber/packed-with-amber.yml
> +      - Defense Evasion::Obfuscated Files or Information [T1027]
@williballenthin  Oh see I left the `.002` sub-technique off because the language specifically calls out software packing as a `method of compressing or encrypting an executable`. While amber does "pack" the given PE into shellcode and subsequently a second PE, and refers to itself as a packer, I could not find evidence that it specifically encrypts or compresses any part of the original PE. Perhaps some encryption is done behind the scenes with SGN, but SGN documentation only refers to "encoding" when describing the transforms to supplied shellcode.

2021-04-22 20:46 UTC, williballenthin commented on anti-analysis/packer/amber/packed-with-amber.yml
> +      - Defense Evasion::Obfuscated Files or Information [T1027]
in the context of capa, we've used .002 to include reasonable forms of packing, such as amber that include encoding (but perhaps not compression nor encryption). this is also in line with contributions we've received from MITRE/ATT&CK authors.

so here, i think we should use .002, though i do appreciate your careful inspection of the ATT&CK technique definitions!

2021-04-23 15:09 UTC, gormaniac commented on anti-analysis/packer/amber/packed-with-amber.yml
> +      - Defense Evasion::Obfuscated Files or Information [T1027]
Good to know! Committed the change.

2021-04-23 22:49 UTC, williballenthin approved these changes

2021-04-23 22:49 UTC, merged

2021-04-23 22:49 UTC, williballenthin commented
thanks @gormaniac !