small fixes
fireeye/capa-rules pull request #390
Opened 2021-05-21 10:16 UTC by ruppde

2021-05-21 15:49 UTC, williballenthin requested changes
see inline suggestion

2021-05-21 15:49 UTC, williballenthin commented on compiler/go/compiled-with-go.yml
> +      - string: "Go buildinf:"
these need to be regexes so that they can match part of a string. typically the buildid string looks like `Go build ID: asdfafdsafdasfasd`

2021-05-21 15:49 UTC, williballenthin commented on nursery/compiled-with-nim.yml
> +      - string: /osalloc\.nim$/
all the rest of these fixes look great, thanks!

2021-05-21 15:49 UTC, williballenthin commented on compiler/go/compiled-with-go.yml
> +      - string: "Go buildinf:"
```suggestion
      - string: /^Go build ID:/
      - string: /go\.buildid/
      - string: /^Go buildinf:/
```

2021-05-21 15:49 UTC, williballenthin commented on compiler/go/compiled-with-go.yml
> +      - string: "Go buildinf:"
these need to be regexes so that they can match part of a string. typically the buildid string looks like `Go build ID: asdfafdsafdasfasd`

2021-06-08 12:58 UTC, mr-tz commented
ping @ruppde 
Can I assist on this?

2021-06-09 08:18 UTC, ruppde commented
ok, it was new to me, that the regular strings in capa don't do a substring search. just came from doing lots of YARA and there it's default unless you use "fullword" ;)

maybe write that explicit in the documentation, just found it here for regex, but no that's the other way around for normal strings:
```
Regexes should be surrounded with / characters. By default, capa uses case-sensitive matching and assumes leading and trailing wildcards. 
```
from https://github.com/fireeye/capa-rules/blob/master/doc/format.md

2021-06-10 11:27 UTC, mr-tz commented
thanks, we're adding the clarification in #414

2021-08-18 20:34 UTC, williballenthin approved these changes

2021-08-18 20:36 UTC, merged

2021-08-23 17:17 UTC, mr-tz commented
thanks, @williballenthin