Added rule for Base64 decoding per 9efa86b43b4367bcdc1591aee59bda25
fireeye/capa-rules pull request #397
Opened 2021-05-25 22:55 UTC by drfuzzer

Added a rule to detect Base64-decoding in an unusual case where the table uses 256 dwords, and was not covered by previous rule.

2021-05-25 23:00 UTC, williballenthin requested changes
see inline suggestions, otherwise, looking good!

2021-05-25 23:00 UTC, williballenthin commented on data-manipulation/encoding/base64/decode-data-using-base64.yml
> +      - bytes: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF F
```suggestion
      - bytes: FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF 3E 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF 3F 00 00 00 34 00 00 00 35 00 00 00 36 00 00 00 37 00 00 00 38 00 00 00 39 00 00 00 3A 00 00 00 3B 00 00 00 3C 00 00 00 3D 00 00 00 FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF = hardcoded base64 translation table (first 64 of 256 dwords)
```

2021-05-25 23:00 UTC, williballenthin commented on data-manipulation/encoding/base64/decode-data-using-base64.yml
> +    name: decode data using Base64
```suggestion
    name: decode data using Base64 via dword translation table
```

updating name to differentiate against the other base64 rule we have (https://github.com/fireeye/capa-rules/blob/master/data-manipulation/encoding/base64/encode-data-using-base64.yml)

2021-05-25 23:00 UTC, williballenthin commented on data-manipulation/encoding/base64/decode-data-using-base64.yml
> +    name: decode data using Base64
will need to change filename to reflect this new name, too

2021-05-25 23:00 UTC, williballenthin commented
can you submit a PR for the testfile, too? https://github.com/fireeye/capa-testfiles/

2021-05-26 07:31 UTC, merged

2021-05-26 07:31 UTC, mr-tz commented
great, thanks!