transmitpackets callback function via wsaioctl
fireeye/capa-rules pull request #456
Opened 2021-08-27 22:38 UTC by jlepore-fe

2021-08-29 22:14 UTC, williballenthin commented on communication/socket/tcp/send/wsaioctl_transmitpackets_callbackfunc.yml
> +    name: obtains TransmitPackets callback function via WSAIoctl
the filename should match the rule name, lowercase and using dashes instead of spaces

2021-08-29 22:17 UTC, williballenthin requested changes
two formatting changes and then ready to merge!

2021-08-29 22:17 UTC, williballenthin commented on communication/socket/tcp/send/wsaioctl_transmitpackets_callbackfunc.yml
> +    name: obtains TransmitPackets callback function via WSAIoctl
the filename should match the rule name, lowercase and using dashes instead of spaces

2021-08-29 22:17 UTC, williballenthin commented on communication/socket/tcp/send/wsaioctl_transmitpackets_callbackfunc.yml
> +    description: The TransmitPackets function transmits in-memory data or file data over a connected socket. The TransmitPackets function uses the operating system cache manager to retrieve file data
for long line, use YAML folded style:
```suggestion
    description: >-
      The TransmitPackets function transmits in-memory data or file data over a connected socket. 
      The TransmitPackets function uses the operating system cache manager to 
      retrieve file data, locking memory for the minimum time required to transmit and 
      resulting in efficient, high-performance transmission.
```

2021-08-29 22:17 UTC, williballenthin commented on communication/socket/tcp/send/wsaioctl_transmitpackets_callbackfunc.yml
> +    description: The TransmitPackets function transmits in-memory data or file data over a connected socket. The TransmitPackets function uses the operating system cache manager to retrieve file data
https://stackoverflow.com/a/3790497/87207

2021-08-29 22:17 UTC, williballenthin commented on communication/socket/tcp/send/wsaioctl_transmitpackets_callbackfunc.yml
> +      - 138C71E94961FE9E31CEC5DFBA62A639:0x100FF55
please open a second PR against https://github.com/fireeye/capa-testfiles/ that adds this file

2021-08-30 09:06 UTC, mr-tz reviewed
I agree with Willi's suggestions. Otherwise, looks great!
You can test/lint the rule locally using `scripts/lint.py` as well.

2021-08-30 16:30 UTC, merged